version: '3.9'
services:
  processor:
    build: .
    environment:
      - REDIS_ADDRESS="redis:6379"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    volumes:
      - .:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
      # container_name: grafana
      # hostname: grafana
    environment:
      -  GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    ports:
      - 3000:3000
